#!/usr/bin/env python3
"""Regenerate the OpenCV oracle fixtures.

    uv run --with opencv-python-headless --with numpy tests/fixtures/generate.py

imgpyr's conventions are chosen to match OpenCV's pyrDown/pyrUp exactly, so any
divergence is a bug on our side. This records OpenCV's answers rather than
depending on it at test time.

scikit-image is not an alternative oracle: pyramid_reduce applies a Gaussian at
sigma = 2*downscale/6 followed by resize, not the 5-tap kernel, so a correct
implementation will disagree with it.
"""

import pathlib
import sys

import cv2
import numpy as np

BORDERS = {"replicate": cv2.BORDER_REPLICATE, "mirror": cv2.BORDER_REFLECT_101}

# pyrUp accepts only BORDER_DEFAULT, which is reflect-101, so the grow path can
# only be compared under mirror.
REDUCE_SIZES = [(8, 8), (9, 7), (7, 9), (16, 16), (33, 25), (5, 5), (4, 3), (101, 7)]
EXPAND_SIZES = [((5, 4), (10, 8)), ((5, 4), (9, 7)), ((4, 4), (8, 8)), ((9, 7), (17, 13))]


def samples(width, height, seed):
    return np.random.default_rng(seed).random((height, width), dtype=np.float32)


def encode(array):
    return " ".join(format(float(v), ".9g") for v in array.flatten())


def main():
    out = []
    skipped = []

    for seed, (width, height) in enumerate(REDUCE_SIZES):
        source = samples(width, height, seed)
        for name, border in BORDERS.items():
            try:
                result = cv2.pyrDown(source, borderType=border)
            except cv2.error as failure:
                skipped.append(f"reduce {name} {width}x{height}: {failure.err.strip()}")
                continue
            out.append(
                f"CASE reduce {name} {width} {height} {result.shape[1]} {result.shape[0]}\n"
                f"IN {encode(source)}\n"
                f"OUT {encode(result)}"
            )

    for seed, ((src_w, src_h), (dst_w, dst_h)) in enumerate(EXPAND_SIZES, start=100):
        source = samples(src_w, src_h, seed)
        try:
            result = cv2.pyrUp(source, dstsize=(dst_w, dst_h))
        except cv2.error as failure:
            skipped.append(f"expand mirror {src_w}x{src_h}->{dst_w}x{dst_h}: {failure.err.strip()}")
            continue
        out.append(
            f"CASE expand mirror {src_w} {src_h} {dst_w} {dst_h}\n"
            f"IN {encode(source)}\n"
            f"OUT {encode(result)}"
        )

    destination = pathlib.Path(__file__).parent / "opencv.txt"
    destination.write_text(
        f"# generated by generate.py against OpenCV {cv2.__version__}\n"
        + "\n".join(out)
        + "\n"
    )

    print(f"{len(out)} cases -> {destination}")
    for note in skipped:
        print(f"skipped {note}", file=sys.stderr)


if __name__ == "__main__":
    main()
